networks:
  rabbitmq-docker-net:
    name: rabbitmq-docker-net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.17.0/24

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=drl_cloud
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  rabbitmq:
      image: rabbitmq:3.11.11-management
      restart: always
      networks:
        rabbitmq-docker-net:
          ipv4_address: 192.168.17.10
      environment:
        TZ: ${TZ}
      volumes:
        - ./RabbitMQ/docker-disks/rabbitmq-data:/var/lib/rabbitmq
        - ./RabbitMQ/docker-disks/rabbitmq-log:/var/log/rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"

  app:
    build:
      context: app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app

  worker:
    build:
      context: app
    command: python worker.py
    restart: always
    depends_on:
      - rabbitmq