networks:
  rabbitmq:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=drl_cloud
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.11.11-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq
    restart: unless-stopped

  app:
    build:
      context: app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app

  worker:
    build:
      context: app
    command: python worker.py
    restart: always
    depends_on:
      - rabbitmq