networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: app
    restart: always
    ports:
      - 5000:5000
    networks:
      - default

  # proxy:
  #   build: proxy
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app
  #   networks:
  #     - default
