networks:
  rabbitmq-docker-net:
    name: rabbitmq-docker-net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.17.0/24

services:
  rabbitmq:
    image: rabbitmq:3.11.11-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - default
    restart: unless-stopped
