networks:
  default:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:

services:
  rabbitmq:
    image: rabbitmq:3.11.11-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
        - default
    restart: unless-stopped