FROM python:3.10

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN apt-get update 
RUN apt-get install -y ffmpeg
RUN ffmpeg -version

COPY . .

CMD ["python", "worker.py"]