name: Pull and Deploy entrega 3

on:
  push:
    branches:
      - release_entrega_3
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: scp into GCP instance
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: 34.132.92.148
          username: jhonnseca0599@gmail.com
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAQEA1aF/J1w/FfI+MZqW9BefklBfwEhNwvlZ12XgIcgaELrURqrE2cto
            Q1Uvc1tXmscAVoo4l1l4uICRNGL19b219awL80UJZfAKSoG7gu2cZK8HclFNxOatNzavHZ
            +szB3nTlRNhEpxQyCp9UmkFGXCY2ENH3X1OoJy1Tl/mWuMtXL7PfhOPkwrU7awmLh2tFj2
            YOX4q1OlTQkt6k3N09lxSrmoFl/sZ3mX5wpQiKN6sSiVkq3DEv8aRckO16a20Uw2g7/24y
            IfHdoY47CJNxDjsXl+oB7+02CUIwY0RkEVauLeBmd5V840LbFAVH8EEq/2mHbIK2ptvBm4
            woNUEURbVQAAA8glfkvBJX5LwQAAAAdzc2gtcnNhAAABAQDVoX8nXD8V8j4xmpb0F5+SUF
            /ASE3C+VnXZeAhyBoQutRGqsTZy2hDVS9zW1eaxwBWijiXWXi4gJE0YvX1vbX1rAvzRQll
            8ApKgbuC7ZxkrwdyUU3E5q03Nq8dn6zMHedOVE2ESnFDIKn1SaQUZcJjYQ0fdfU6gnLVOX
            +Za4y1cvs9+E4+TCtTtrCYuHa0WPZg5firU6VNCS3qTc3T2XFKuagWX+xneZfnClCIo3qx
            KJWSrcMS/xpFyQ7XprbRTDaDv/bjIh8d2hjjsIk3EOOxeX6gHv7TYJQjBjRGQRVq4t4GZ3
            lXzjQtsUBUfwQSr/aYdsgram28GbjCg1QRRFtVAAAAAwEAAQAAAQAgyxruA5jSiV5XNnwU
            Kbku2GQua9r2AllyeXrDrMglh8x0sZuotDMD3QR88Ilc4s3wOuUPhKZFqkS/9i38BFx1gy
            zNcexMp+GoiMwsP8XZZc3elFD8GA4AcwZEJaH8rl12tnW0yEmlLJMyalTD5dAGedwuF2km
            y2YNybcG6c3Of3loKFkFxdlh8nErhtPZD5A1IgpbgEsP/5sRwFo5J89ceO49JzsRvz098T
            RHd0O1OrV7j6xUMxt7csyMEePkrCA8mgCJSyzskGZLNUUkBOrxH/Zwb3DjmzQEMXh0tJ4x
            Jt9dq1vU2SWWWMARYrxwf5r5Lhr2y8IlyawNiWDzsVMxAAAAgC1L6YilMrGQFVJ6a5giPp
            EZbiftXdidxHVh2lAdwAEqnnylsW4RokXPph9YCV9exGZ75cOBs/6J5v1UAyAYyIpXNKuN
            luNMLV72QwzTHVuBs9J8B2CgDFiA+I/VN6PBzLIzjxKytpL0Wy20twcJ/LpF8a1V/rAhD8
            zMp5O/P1QZAAAAgQD0ai9ubKcwg9QmQWRSPArw+ibAM/nikrz42UyXKX9XZn2cgfQ0us2q
            Y4QjXe6xyfjNfByBXuCN+0imJxnmsMDdwM2Ctfie0b5KDW49XKBGbZNyS8jV0lECeeDH8Q
            QeKAbxya/69eEpCQ7pzZCpyui6zMsiSyDeiYJOzgZksB+u5QAAAIEA38HErwjZEk31Z/hF
            zNJZoXRayGKe1yXK/MAMULdd+Zeu+eYHcGyiLpbLhPW84PaLu/F2UVmlMCqPEPwQjsqKWA
            lvR21gtwVJ45/ISIZuu3TmDYpu0o3fwgZYUbExuJXiM4mnzKa4u6+dhj4VCtyW3dOR12KZ
            uwdCpg+nc05Uw7EAAAANamhvbm5zZWNhMDU5OQECAwQFBg==
            -----END OPENSSH PRIVATE KEY-----
          run: echo “Login exitoso”

