name: Pull and Deploy entrega 3

on:
  push:
    branches:
      - release_entrega_3
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: braided-gist-419517
          service_account_key: |
            {
                "type": "service_account",
                "project_id": "braided-gist-419517",
                "private_key_id": "d640ca82bff82481b354ec1050a55190d2d5dc31",
                "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCa+Zjjr02ZpUca\nQK49p/GwPcziHjJ6UFyZnJ+VBXvyOoMt4gFq0j5pezbLTe7M0sW7LDh5ck/29eL1\nCxtUsdfiozb3GQq1KyMQNieP98MvKMaZmjZT7c7esyPQfdeSg0m+x307GOWiTVnL\nWQqG9NbKfve1IxdVg6YtxZlkhpjbTYML/DLBq9Y5TiehvrKq0KMFlCRu4DXUoUEk\nAPi9FnE0tpZd6GRLAAqXTZ0SMmTAn/HMi8JQs4IsDLX5/gnRDxp4Q7wi9F/DC24c\nB0ZuzNlMMYs1SmM5b+khnbHtsAdnJ9u2+S8ocPaMg3sWosDEYSz2rbeZ4m0ClSN7\nCSCGPSBjAgMBAAECggEAEI9zHi10ROK2TjYIMzAi8bArmHlymm3Dn2nvBvJ0Pruw\nRd28mgjHwOd466ZdyhxhzcZZbeeLElBPMDE/epWbL1g9Pjq6UVwVM0fI2Ce5Ke0Z\nCn6XUfD7u1d4Oxt0xu6+7s3hch25zYCng5p1t1sq0q5Y/k220h1Zy31YjrdFVqBv\nZTV76Vf3gfTGweqtJrEFtiruMYwJ2R8z8WaEXlK4WBGn9vzryVqOAQF1XdsiWuWg\nFBTGYeTd69sE3E+rcb9SjyIXnQvG/NAGf9sxKcWm06HG6IktiwVcGtt5KWZWdhkP\nr9eNhE8es7hS74lghNnyUKqsn9B9ORTefRZJNelWBQKBgQDH70x3/P5o4oNe1aW5\ncmjG/K2ECBiYwpqwXiYp4J/6joNy8Sfe2WgLFQj/1xD6sP/1lXFLCk/FIRN2+NSN\nNgKSn5gvNBSnSpIRu385aVcbG98WPKcvZMAmGwyjNDw+40+4vWif4RiatxDIsuhX\n7+2Ua6uFVpYMEoGmH4bO6xg0HwKBgQDGbsZdZSVLyNIhU35CMFCMEGIjcH0f5o3N\n1xLTHpyXF+KuCSNWXoezJkqL/W0DqE8xlwwL3UqQofpb9lQZtA4Pk4h/X01uynp4\nb/HMICIswca8jwPc5u/mHEPjsqcwy9m6gSgDAqv6Rk3hX7CJornZKWz5h7Tpf4nd\nMZz7FFirPQKBgQCPLFMTPa2lyEeRGuehZEeZ74oGGZIbmogRsmob5QpK79E792u4\nzvENtpOKOiWjkCrLX6gQt6KmJOh+cvQq5zlybC0b6Gy92828OwuBPmktNYlMsER8\n0OY0o3wqRxa5ZihJwAFzNEtdR6kSP+PYTS1R8sSSKI4suPf00XDFLl9XuwKBgQCD\nrD40+0kkYL4PHzhI84Z/at+0ZJCi+npefLkhHs8J8++XTLkGNvQVDPOqsSAFrUnf\nvjtgJBe2ocVgALUN2Uz7SQrqenMHcZSTFrV8nlYPHQajWMNXcmb+awMhtQr8dkik\nWdATL1KvYLeNNdIPgsuQLs0BR+vkhZ0WCjYA5h9wgQKBgGA/8wlHi1PlghqKmtJI\ny655l7ddw9OxweKADkvQiB6a3q26CiF2sErjyggDlNNNRpXRxZcjWW6zzCoWjaxq\nx8IeqlqROZ1QA4gZn9O8h3IWrAYALJVqt8gIbJPzSl/et/byr1AbyR0NJPgKmZBG\nSD8K6csDbGYKySHp2OXZQjN2\n-----END PRIVATE KEY-----\n",
                "client_email": "835221722819-compute@developer.gserviceaccount.com",
                "client_id": "100214115841146982090",
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/835221722819-compute%40developer.gserviceaccount.com",
                "universe_domain": "googleapis.com"
              }
          export_default_credentials: true

      - name: scp into GCP instance
        uses: appleboy/scp-action@master
        with:
          host: 34.132.92.148
          username: jhonnseca0599@gmail.com
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAQEA1aF/J1w/FfI+MZqW9BefklBfwEhNwvlZ12XgIcgaELrURqrE2cto
            Q1Uvc1tXmscAVoo4l1l4uICRNGL19b219awL80UJZfAKSoG7gu2cZK8HclFNxOatNzavHZ
            +szB3nTlRNhEpxQyCp9UmkFGXCY2ENH3X1OoJy1Tl/mWuMtXL7PfhOPkwrU7awmLh2tFj2
            YOX4q1OlTQkt6k3N09lxSrmoFl/sZ3mX5wpQiKN6sSiVkq3DEv8aRckO16a20Uw2g7/24y
            IfHdoY47CJNxDjsXl+oB7+02CUIwY0RkEVauLeBmd5V840LbFAVH8EEq/2mHbIK2ptvBm4
            woNUEURbVQAAA8glfkvBJX5LwQAAAAdzc2gtcnNhAAABAQDVoX8nXD8V8j4xmpb0F5+SUF
            /ASE3C+VnXZeAhyBoQutRGqsTZy2hDVS9zW1eaxwBWijiXWXi4gJE0YvX1vbX1rAvzRQll
            8ApKgbuC7ZxkrwdyUU3E5q03Nq8dn6zMHedOVE2ESnFDIKn1SaQUZcJjYQ0fdfU6gnLVOX
            +Za4y1cvs9+E4+TCtTtrCYuHa0WPZg5firU6VNCS3qTc3T2XFKuagWX+xneZfnClCIo3qx
            KJWSrcMS/xpFyQ7XprbRTDaDv/bjIh8d2hjjsIk3EOOxeX6gHv7TYJQjBjRGQRVq4t4GZ3
            lXzjQtsUBUfwQSr/aYdsgram28GbjCg1QRRFtVAAAAAwEAAQAAAQAgyxruA5jSiV5XNnwU
            Kbku2GQua9r2AllyeXrDrMglh8x0sZuotDMD3QR88Ilc4s3wOuUPhKZFqkS/9i38BFx1gy
            zNcexMp+GoiMwsP8XZZc3elFD8GA4AcwZEJaH8rl12tnW0yEmlLJMyalTD5dAGedwuF2km
            y2YNybcG6c3Of3loKFkFxdlh8nErhtPZD5A1IgpbgEsP/5sRwFo5J89ceO49JzsRvz098T
            RHd0O1OrV7j6xUMxt7csyMEePkrCA8mgCJSyzskGZLNUUkBOrxH/Zwb3DjmzQEMXh0tJ4x
            Jt9dq1vU2SWWWMARYrxwf5r5Lhr2y8IlyawNiWDzsVMxAAAAgC1L6YilMrGQFVJ6a5giPp
            EZbiftXdidxHVh2lAdwAEqnnylsW4RokXPph9YCV9exGZ75cOBs/6J5v1UAyAYyIpXNKuN
            luNMLV72QwzTHVuBs9J8B2CgDFiA+I/VN6PBzLIzjxKytpL0Wy20twcJ/LpF8a1V/rAhD8
            zMp5O/P1QZAAAAgQD0ai9ubKcwg9QmQWRSPArw+ibAM/nikrz42UyXKX9XZn2cgfQ0us2q
            Y4QjXe6xyfjNfByBXuCN+0imJxnmsMDdwM2Ctfie0b5KDW49XKBGbZNyS8jV0lECeeDH8Q
            QeKAbxya/69eEpCQ7pzZCpyui6zMsiSyDeiYJOzgZksB+u5QAAAIEA38HErwjZEk31Z/hF
            zNJZoXRayGKe1yXK/MAMULdd+Zeu+eYHcGyiLpbLhPW84PaLu/F2UVmlMCqPEPwQjsqKWA
            lvR21gtwVJ45/ISIZuu3TmDYpu0o3fwgZYUbExuJXiM4mnzKa4u6+dhj4VCtyW3dOR12KZ
            uwdCpg+nc05Uw7EAAAANamhvbm5zZWNhMDU5OQECAwQFBg==
            -----END OPENSSH PRIVATE KEY-----
          run: echo “Login exitoso”

