name: Pull and Deploy entrega 3

on:
  push:
    branches:
      - release_entrega_3
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAsRkSdxAGv3t2i81kFlMuPShCvwyzw/iKlDBgktQVo/UCA3D2SVb4
            /wl+HKeE8BSgfkk2YGzrhVEj6b14lmuTik4KAw8g1P1QeMpoAVYm44I10+dzNtXbWMzI+k
            Zz9kQITFZ5SI1khuGZQ2sTVmbIOiLcl10USm96MXyrmTwPL/lNjCAJh25tr8Q6fMfKx7m8
            I6huRi7/zC3Y2tFIhh1e5yOcWdQsJusLD/xUk3FUzPqKBXcNDg0jx5X37Yf9CrjTA/A3QX
            /ke3nZX8rEHmezgGTDlGp9WHi8LKocrbhkEy18xaQj7DkRM0IVoxSozi2HfdNi/sn4A6gY
            Zm8hNb2BEFlSty4RZhhRvW9mrH42psCYjx3+i5mWy4SUmKujvexhE8eD19P20jH1g9CUg3
            PuLPb63rlxNoEr6Q1jdUKdAEO0Mb8nEgRFxrVym/DAB9gzWuA9iNqh9I0d8JMcCEwsC/4m
            nuEBqKz5FxF2G2ZnRHmOGkiUfND1SCXK2nuNARspAAAFwNxDVnbcQ1Z2AAAAB3NzaC1yc2
            EAAAGBALEZEncQBr97dovNZBZTLj0oQr8Ms8P4ipQwYJLUFaP1AgNw9klW+P8JfhynhPAU
            oH5JNmBs64VRI+m9eJZrk4pOCgMPINT9UHjKaAFWJuOCNdPnczbV21jMyPpGc/ZECExWeU
            iNZIbhmUNrE1ZmyDoi3JddFEpvejF8q5k8Dy/5TYwgCYduba/EOnzHyse5vCOobkYu/8wt
            2NrRSIYdXucjnFnULCbrCw/8VJNxVMz6igV3DQ4NI8eV9+2H/Qq40wPwN0F/5Ht52V/KxB
            5ns4Bkw5RqfVh4vCyqHK24ZBMtfMWkI+w5ETNCFaMUqM4th33TYv7J+AOoGGZvITW9gRBZ
            UrcuEWYYUb1vZqx+NqbAmI8d/ouZlsuElJiro73sYRPHg9fT9tIx9YPQlINz7iz2+t65cT
            aBK+kNY3VCnQBDtDG/JxIERca1cpvwwAfYM1rgPYjaofSNHfCTHAhMLAv+Jp7hAais+RcR
            dhtmZ0R5jhpIlHzQ9Uglytp7jQEbKQAAAAMBAAEAAAGABGAiFN4Tn/AXGFe+Da/8WW9jlx
            3jWaJ2sGKxxM2XuMiv22xTW3HE3mPqcUm2xunoOA0175k1UvfeSdMVdgLzqYlpetSeeytZ
            4q1z4cznp6aYOZ4d773bfjogtjqezhfKzDG1QVSD+7H6eUrS7ByHPSokFjB1qkFO7QbUub
            PHt3KC3C/PncszINJPHyAzu4OfDpL7DCxzA7qMwXBFs6bpXmTX+F9d1WV918U5r426OoPE
            p03/El4tqIEFLSxXVUgxHPT/56P7a6N0ZcQzx2UpCut8/1xGVNaRSHLM9ekvmvNNr8mFP0
            SOErxI2TIyCZnZGv31QEsqk4mbSnFtX70KcTqw0rQqrUlUlPiGhfrm3MpKEUr593T+UowJ
            w/EEZED4gvjIBUy9dmZBy2JCcm9ePnCV+hEn2SKVqmqvAmELkmjHiSaEJC3JW874lTQNG/
            1aP2cKEcz/F+Nbgpw1Z3wqZs/rF18Tx/rZlcUaDzZ6wYLcgqbhhUZn3dMj9YFJEM1xAAAA
            wQCuN0jiKk4b7gj+S+DDBhykYn8vW81T1DW1JRpEK0M/9uJ0Nqc/PXAvQSZSUMsL5hSa8q
            Y1EN7iQ5P1Cep4gExqjb4BtvdN03M5FYsyIn7odfm61Vzi4J3nOx5eIB7/Z16u0GH2ForH
            lxhLn3BW1AwlzixGugV0keDRU3BvOHoqjVe2xWOEOwZG/VWTTOkLd611KQENQFMhzdWGgV
            +Pmax6v7o5KLtgDMrfUJcVWD/e4ZFlmS71pzFukrrYyW1yTacAAADBAN3JtRj5HqOMD4by
            V7M7X0444i6msVq0GsMAVmvpBKyIihrkxLTtbHPpYZwuiOGmWNZ/PHk6reK2kX5goMlUlj
            1vIfsA5IK4BPi+Pef1lKTuxHveiIoHEvxjA54Yc9yOQgGyLj2DCNv7v+S4TSqxVUM40uaA
            Szb+k3x0iG/Ev4kNSobZHRw/BRIoeOtu3qHah+ZvIIA76hBEFDGVavshdfhdh4UMj8fOnz
            kG5SzvpZQKED8ExqfEHHcJPk2nrR8u8QAAAMEAzGqUedkncG5s0LGnr1TQFSDiu3xKj3Y7
            eVdxrblyVqTz3WE/7p6gSACD41GtGFVz8NRaO+WzHZ05+2VwxzM++9DaVEq7oPPSvrupKK
            aDPTWDsZYtqk5tdSdTwc37MjZjpK00pu39HGRAmbeotp3FUu8RpYB1kCNPqgYVL7xc1lCK
            jPnmg62tLK6x0VhSmypQ14USVZk/Y+NQx0oocMRAs+EJdSxHf38eBs1ScCW/WiIBTZHrLM
            1EgCLIOUjpWR+5AAAARWpob25uc2VjYTA1OTlAd2ViLXNlcnZlci51cy1jZW50cmFsMS1j
            LmMuYnJhaWRlZC1naXN0LTQxOTUxNy5pbnRlcm5hbAECAwQF
            -----END OPENSSH PRIVATE KEY-----
            
      - name: Check directory existence
        run: ssh -o StrictHostKeyChecking=no jhonnseca0599@34.132.92.148 'echo "Perfect login"'

